---
on:
  push:
    branches:
      - main
    paths:
      '**.proto'
    tags-ignore:
      - "**"
name: proto-sync
jobs:
  sync-repoa:
    steps:
      first:
        - name: First repo
          uses: ssh2003/source-for-sync/.github/workflows/on-proto-update.yml@main
          secrets: inherit
          with:
            repo: "ssh2003/target-for-sync"
      second:
        - name: Second repo
          uses: ssh2003/source-for-sync/.github/workflows/on-proto-update.yml@main
          secrets: inherit
          with:
            repo: "ssh2003/second-target-for-sync"
