---
on:
  push:
    branches:
      - main
    paths:
      '**.proto'
    tags-ignore:
      - "**"

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GH_TOKEN }}
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
  get-repos-list:
    runs-on: ubuntu-latest
    outputs:
      REPOS: ${{ steps.get-repos.outputs.repos }}
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GH_TOKEN }}
      - name: get repos list
        id: get-repos
        #run: echo ::set-output name=repos::$(cat .repos-for-proto-sync.txt)
        run: echo "repos=one" >> "$GITHUB_OUTPUT"
      - name: show output
        run: echo ${{ steps.get-repos.outputs.repos }}
  test-job-for-outputs:
    runs-on: ubuntu-latest
    needs: get-repos-list
    steps:
      - env:
          REPOS: "${{ needs.get-repos-list.repos }}"
        run: echo "${{ env.REPOS }}"

  # update-proto:
  #   needs: get-repos-list
  #   uses: ssh2003/source-for-sync/.github/workflows/on-proto-update.yml@main
  #   secrets: inherit
  #   with:
  #     repo: ${{ needs.get-repos-list.repos }}
  #     #repo: "['ssh2003/target-for-sync', 'ssh2003/second-target-to-sync']"
