---
on:
  push:
    branches:
      - main
    paths: "**.proto"
    tags-ignore:
      - "**"
jobs:
  update-proto:
    uses: ssh2003/source-for-sync/.github/workflows/on-proto-update.yml@main
    secrets: inherit
    with:
       repo: "${{ vars.REPOS_TO_SYNC }}"
