---
on:
  push:
    branches:
      - main
    paths: "**.proto"
    tags-ignore:
      - "**"
jobs:
  test-vars:
    runs-on: ubuntu-latest
    steps:
      - name: vars
        run: |
          echo ${{ fromJson(vars.REPOS_TO_SYNC) }}
          echo ${{ toJson(vars.REPOS_TO_SYNC) }}
  update-proto:
    uses: ssh2003/source-for-sync/.github/workflows/on-proto-update.yml@main
    secrets: inherit
    with:
      repo: ${{ toJson('ssh2003/target-for-sync','ssh2003/second-target-to-sync') }}
       #repo: "${{ toJson(vars.REPOS_TO_SYNC) }}"
       #repo: "['ssh2003/target-for-sync', 'ssh2003/second-target-to-sync']"
